services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/var/www/app_name
    depends_on:
      - db
    # environment:
    #   - MONGODB_HOST=localhost
    #   - MONGODB_PORT=27017
    #   - MONGODB_USER=root
    #   - MONGODB_PASSWORD=123123
    #   - RAILS_ENV=development
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - red
      - app
    ports:
      - 8080:80
      # - 8080:80
  red:
    image: node_red
    # build: 
    #   context: .
    #   dockerfile: ./docker/red/Dockerfile
  # web:
  #   build: .
  #   command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  #   volumes:
  #     - .:/myapp
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db